### ISSUE TITLE
Build on macOS

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/portaudio-feedstock#2]
Looks like it is possible to build this on macOS. Would be nice to have a macOS build of it.

ref: http://portaudio.com/docs/v19-doxydocs/compile_mac_coreaudio.html

**Comment by traversaro** [comment]
For anyone interested in this, I noticed that the `AnacondaRecipes` fork of this repos has macOS build support, see https://github.com/conda-forge/portaudio-feedstock/compare/master...AnacondaRecipes:master .

**Comment by scopatz** [comment]
PRs welcome!

**Comment by cbrnr** [comment]
So would the patch work with this package? Or are there any additional changes that need to be implemented?

**Comment by scopatz** [comment]
It is probably worth a try

**Comment by cbrnr** [comment]
I don't have the time to do that right now, mainly because I am totally unfamiliar with both Anaconda/conda-forge and this package. Could you maybe explain what the difference is between this recipe and the one from Anaconda? Would copying the Anaconda recipe be a viable option? Even if these recipes are 100% identical it would be useful because then people wouldn't have to mix channels and could work with conda-forge-only packages.

**Comment by scopatz** [comment]
The difference between this and anaconda is the ownership and maintenance. Porting fixes from the anaconda one is totally Ok as long as they follow the BSD-3-Clause license

**Comment by traversaro** [comment]
A new portaudio version should be released soon with a CMake-based build system (see https://github.com/PortAudio/portaudio/pull/465), so an alternative is to switch to use the CMake-based build system, at in that case targeting macOS may be easier.

**Comment by jakirkham** [comment]
Well macOS already supports autoconf-style builds. It’s just a question of making sure the dependencies are available and doing the build
